pipeline {
    agent any 
    stages {
        stage('Static Analysis') {
            steps {
                echo 'Hello , I am Ashna kabsuri' 
            }
        }
        stage('Compile') {
            steps {
                echo 'This is for devops Exp5' 
            }
        }
        stage('Security Check') {
            steps {
                echo 'Run the security check against the application' 
            }
        }
        stage('Run Unit Tests') {
            steps {
                echo 'Welcome' 
            }
        }
        stage('Run Integration Tests') {
            steps {
                echo 'Run only crucial integration tests from the source code' 
            }
        }
        stage('Publish Artifacts') {
            steps {
                echo 'Thank you' 
                echo 'Bye' 
            }
        }
    }
}
